# autogenerated by txs
#include:etoolbox
#include:tikz
\__file_name=etoolbox.sty#S
\__file_name=tikz.sty#S
\__hook etoolbox#S
\__hook package/etoolbox/after#S
\__hook package/etoolbox/before#S
\__hook package/tikz/after#S
\__hook package/tikz/before#S
\__hook tikz#S
\__hook_next package/etoolbox/after#S
\__hook_next package/etoolbox/before#S
\__hook_next package/tikz/after#S
\__hook_next package/tikz/before#S
\__hook_toplevel package/etoolbox/after#S
\__hook_toplevel package/etoolbox/before#S
\__hook_toplevel package/tikz/after#S
\__hook_toplevel package/tikz/before#S
\g__hook_package/etoolbox/after_code_prop#S
\g__hook_package/etoolbox/after_reversed_tl#S
\g__hook_package/etoolbox/before_code_prop#S
\g__hook_package/etoolbox/before_reversed_tl#S
\g__hook_package/tikz/after_code_prop#S
\g__hook_package/tikz/after_reversed_tl#S
\g__hook_package/tikz/before_code_prop#S
\g__hook_package/tikz/before_reversed_tl#S
\unprocessedoptions-etoolbox.sty#S
\unprocessedoptions-tikz.sty#S
csnameendcsname#S
etoolbox.sty#S
tikz.sty#S
